language: python
python:
  - "3.6"

services:
  - postgresql

# command to install dependencies
install: "pip3 install -r requirements.txt"

# env:
#   global:
#   - DATABASE_URI='postgres://postgres:@localhost:5432/testdb'

# before_script:
#   - psql -c 'create database testdb;' -U postgres

# command to run tests
script: nosetests

after_success:
 - codecov
